# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Yarn Build

on:
  push:
    branches: [ main, development, staging ]
  pull_request:
    branches: [ main, development, staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: (env | grep -e KS_ >> .env) || true
    - run: (env | grep -e NEXT_PUBLIC_ >> .env) || true
    - run: (env | grep -e AURORA_ >> .env) || true
    - run: (env | grep -e SECRET_COOKIE_PASSWORD >> .env) || true
    - run: (env | grep -e FRONTEND_URL >> .env) || true
    - run: yarn install
    - run: yarn run plugin pull
    - run: yarn run plugin build
    - run: yarn build
    - run: mkdir -p /home/runner/.npm
